name: Build and Test
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - node-version: 16.x # See https://nodejs.org/en/about/releases/

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: |
          npm ci  # client dependencies
          pushd server
          npm ci  # server dependencies
          popd

      - name: Server Lint and Build
        run: npm run build:server

      - name: Client Lint and Build
        run: npm run build:client
        env:
          VITE_ENABLE_LOGIN: true
          VITE_ENABLE_SIGNUP: true
          VITE_PUBNUB_SUBSCRIBE_KEY: ${{ secrets.VITE_PUBNUB_SUBSCRIBE_KEY }}

      - name: Unit Tests
        run: npm test

      - name: Pull Vercel Environment Information
        run: |
          cd server
          ./node_modules/.bin/vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          cd server
          ./node_modules/.bin/vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Preview
        run: |
          cd server
          ./node_modules/.bin/vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
